name: deploy-web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.49.0
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination '$web' \
              --source . \
              --auth-mode key \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}
  